services:
  catalyst_app_db:
    image: postgres
    volumes:
        - "./pgdata:/var/lib/postgresql/data"
    ports:
        - ${LOCAL_IP:-127.0.0.1}:${DB_LOCAL_PORT:-5432}:5432
#        - "5432:5432"
    restart: always
    environment:
       POSTGRES_PASSWORD: db_pass
       POSTGRES_USER: db_user
       POSTGRES_DB: db
    networks:
        - catalyst_app_network

  catalyst_app_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
        - "./src:/opt/app"
    command: "./MyApp/script/myapp_server.pl --restart"
    ports:
        - "3000:3000"
    restart: always
    links:
        - "catalyst_app_db"
    networks:
        - catalyst_app_network

networks:
  catalyst_app_network:
    driver: bridge
